### ISSUE TITLE
CCEmuX

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/howl.ci#1]
> We could either use CCEmuX or roll our own.
> 
> I'm going to need to inject custom APIs into the environment (to allow passing environment variables, marking the build as failed, etc...) so it might be more beneficial to roll my own. If we do go that route then I'd want it to be compatible with CCEmuX: the ci API should provide the same methods and allow setting the same config values.
> 
> The advantage of using CCEmuX is that we don't need to bother remaining compatible with other emulators, and we get all the nifty features that are already there.

---

> In the short term it was easier to dash up something together in a couple of hours then add what I wanted to CCEmuX. However, I don't really want to be developing an emulator here: there are a ton of features missing that I've no inclination to add, hopefully CCEmuX will fill that gap.

**Comment by dmarcuse** [comment]
I'm more than happy to implement necessary features into CCEmuX, and I've been meaning to make it more library-like (i.e. easier way to register custom APIs) for a while anyways.

**Comment by SquidDev** [comment]
Whilst it would be nice to do, it's probably going to be easier just to stick with the current emulator for the time being. We don't need all the fancy features that CCEmuX provides, and shipping our own allows us to keep things as simple as possible.
