### ISSUE TITLE
Not working with CC 1.75?

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/howl.ci#10]
I'm trying to run the 'runner' locally but it's getting various Java exceptions (another pops up as I hack around it in the code); the code is referencing things that appear not to exist in CC 1.75. I'm confused as to how this is the case as it appears to work fine according to the website. Maybe those builds were before the breaking changes?

**Comment by ghost** [comment]
Ah yeah nevermind, sorry. I can see the commit that caused this...

**Comment by SquidDev** [comment]
The old version downloads + documentation should still be around, it's just CC changed an awful lot internally, and it wasn't worth supporting all versions.

**Comment by ghost** [comment]
@SquidDev I've struggled to find a version compatible with 1.75; I guess 0.1 is an option? Not 0.1.13...

Actually even 0.1 isn't working; InvocationTargetException

Nor can I compile it; getting a 403 trying to download the CC xml file

**Comment by SquidDev** [comment]
0.1.9 should work: [here's what I use for Howl itself](https://github.com/SquidDev-CC/Howl/blob/master/.travis.yml) (not that I've tested it in a while).

**Comment by ghost** [comment]
Ah, that works! Thank you!

In other news, I'd sure love to see continued development on howl.ci and Howl if applicable. Might try to do some work if I can find the time...

**Comment by SquidDev** [comment]
Fantastic! 

Yeah, I haven't done a lot of programming within CC Lua recently, and `require` rather made Howl redundant, so I haven't done a lot of work on either recently. There's always things I'd like to improve, I just have other projects which take priority sadly. Do PR something or get in touch if you're missing something though.

**Comment by ghost** [comment]
Sure thing! I too have way too much going on at the moment but, it's just hard to see something so well-made die, you know? And, though I'm certainly the minority, .. well.. long live CC 1.75!

**Comment by SquidDev** [comment]
> long live CC 1.75

But palettes, and sub-pixels, and no more string bug! It'd be kinda nice if CC's core libraries could be shared across versions, but sadly too much changes for that ever to be practical.

**Comment by ghost** [comment]
Indeed. But I can't play past 1.7.10.
