### ISSUE TITLE
Not all arbitrary URLs work

### ISSUE THREAD

**Issue by ghost** [SquidDev-CC/howl.ci#11]
It seems that URLs that don't have an extension aren't working. This may not be the root issue but this is the case for every URL I've tried that has no extension. For example: https://termbin.com/se1z

Okay this isn't quite true; this one works: https://gist.githubusercontent.com/sci4me/98fd755fcc50ae15ac47d1167a7e3c75/raw

**Comment by SquidDev** [comment]
As mentioned on IRC, it doesn't look like there's anything I can do there - the site blocks any remote requests and short of setting up a proxy and fetching them on an actual server rather than JS, I don't think there's anything I can do.
